dbt_amazon:
  outputs:
    dev:
      account: msbvvdx/sh23127
      database: AMAZON_DB
      password: Snowflake@1694
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: JAGADEEP973
      warehouse: COMPUTE_WH
  target: dev
fedex_dbt:
  outputs:
    dev:
      account: msbvvdx-sh23127
      database: AMAZON_DB
      password: Snowflake@1694
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 2
      type: snowflake
      user: Jagadeep973
      warehouse: COMPUTE_WH
  target: dev
fedex_dbt_proj:
  outputs:
    dev:
      account: amazon_data
      database: amazon_db
      password: '123456'
      role: ACCOUNTADMIN
      schema: fedex_analysis_data
      threads: 1
      type: snowflake
      user: jagadeep
      warehouse: Amazon_wh
  target: dev
