dbt_amazon:
  outputs:
    dev:
      account: msbvvdx/sh23127
      database: AMAZON_DB
      password: Snowflake@1694
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: JAGADEEP973
      warehouse: COMPUTE_WH
  target: dev
fedex_dbt:
  outputs:
    dev:
      account: msbvvdx-sh23127
      database: AMAZON_DB
      password: Snowflake@1694
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 2
      type: snowflake
      user: Jagadeep973
      warehouse: COMPUTE_WH
  target: dev
