
version: 2

models:
  - name: Orders_fact
    description: ""
    columns:
      - name: Amount
        description: "The primary key for this table"
        tests:
          - negative_amount_check

  # - name: my_second_dbt_model
  #   description: "A starter dbt model"
  #   columns:
  #     - name: id
  #       description: "The primary key for this table"
  #       data_tests:
  #         - unique
  #         - not_null
